services:
  welcome-admin:
    image: anssi/fcsc2024-web-welcome-admin:latest
    ports:
      - "8000:8000"
  welcome-admin-db:
    image: postgres:16
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
